/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Native-Encoding-Detection.h
 #	source generated by 4D Plugin Wizard
 #	Project : Native Encoding Detection
 #	author : miyako
 #	2021/04/24
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_NATIVE_ENCODING_DETECTION_H
#define PLUGIN_NATIVE_ENCODING_DETECTION_H

#if VERSIONWIN
// Must come before anything that can transitively include <windows.h>
// (4DPluginAPI.h, then <mlang.h> below both can). <windows.h> auto-includes
// the legacy <winsock.h> unless WIN32_LEAN_AND_MEAN is already defined or
// <winsock2.h> has already been included. <mlang.h>'s own include chain in
// current Windows SDKs (confirmed against 10.0.26100.0 in CI) pulls in
// <winsock2.h>/<ws2tcpip.h>. Getting both winsock generations into one TU is
// what produces the "struct type redefinition" / "redefinition; different
// linkage" cascade — <winsock.h> guards itself against a prior <winsock2.h>
// inclusion via _WINSOCKAPI_, so including it first here neutralizes any
// later attempt to pull in the old header, regardless of what 4DPluginAPI.h
// or <mlang.h> do internally.
#include <winsock2.h>
#endif

#include "4DPluginAPI.h"

#if VERSIONWIN
#include <mlang.h>
#else
#include <CoreServices/CoreServices.h>
#define MAX_LENGTH_FOR_ENCODING_NAME (255)
#endif

#include "4DPlugin-JSON.h"

#pragma mark -

void NED_Detect_encoding(PA_PluginParameters params);

#endif /* PLUGIN_NATIVE_ENCODING_DETECTION_H */
