/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Native-Encoding-Detection.h
 #	source generated by 4D Plugin Wizard
 #	Project : Native Encoding Detection
 #	author : miyako
 #	2021/04/24
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_NATIVE_ENCODING_DETECTION_H
#define PLUGIN_NATIVE_ENCODING_DETECTION_H

#include "4DPluginAPI.h"

#if VERSIONWIN
#include <mlang.h>
#else
#include <CoreServices/CoreServices.h>
#define MAX_LENGTH_FOR_ENCODING_NAME (255)
#endif

#include "4DPlugin-JSON.h"

#pragma mark -

void NED_Detect_encoding(PA_PluginParameters params);

#endif /* PLUGIN_NATIVE_ENCODING_DETECTION_H */
